[package]
name = "cosmogony2cities"
version = "0.1.0"
authors = ["antoine-de <antoine.desbordes@gmail.com>"]
edition = "2018"

[dependencies]
cosmogony = "0.3"
diesel = "1.4"
structopt = "0.2"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.6"
failure = "0.1"
geo = "0.6"
itertools = "0.8"
