name: Build packages 

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: navitia/debian8_dev

    steps:
    - uses: actions/checkout@v1
    - name: install rust toolchain
      run: |
        apt update
        apt install -y curl
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > get_rust.sh
        sh get_rust.sh -y
        . $HOME/.cargo/env
        rustup update
    - name: install packaging tool
      run: |
        . $HOME/.cargo/env
        cargo install --force cargo-deb
    - name: create packages
      run: |
        . $HOME/.cargo/env
        cargo deb
    - name: upload debian packages
      uses: actions/upload-artifact@v2
      with:
        name: archive
        path: target/debian/*.deb
